### ISSUE TITLE
install.sh broken on OSX

### ISSUE THREAD

**Issue by conradkdotcom** [conradkdotcom/rooster#16]
`install.sh` is broken on OSX. From what I hear, the problem is with the `sha256sum` command: it exists on Linux but not on OSX. OSX uses `shasum -a 256` instead.

Tasks:
- [x] on OSX, use `shasum -a 256` instead of `sha256sum` in `install.sh`
- [ ] install dependencies via `brew` or `port`
- [x] test if it works on OSX
- [x] test if it works on other linux distros
- [x] add yourself to the contributors' list in `README.md` in alphabetical order

To check for OSX, you can use something like this:
```bash
if [ "`uname`" = "Darwin" ]; then
    # code for osx, ie shasum -a 256 ...
else
    # code for other OSes, ie sha256sum ...
fi
```

Thanks a lot for your help ❤️ If you have any questions, just let us know and we'll jump in to help.

**Comment by varin-pierre** [comment]
*Fix script* for macOS [cp /usr/local/bin/rooster], test on macOS 10.12.5 and Ubuntu 16.4.2

**Comment by hvze** [comment]
I'm currently working on a fix for this, do you know what dependencies we need from homebrew?

**Comment by conradkdotcom** [comment]
@hvze Woops, my bad for not closing this issue before. I think this is fixed already by @varin-pierre.

Could you try if you get a chance please ? I don't know what dependencies would be required, but I think `python3` and `pkg-config` would be the only ones.

**Comment by hvze** [comment]
I grabbed the latest version off and there were still a couple issues with the script calling things it shouldn't have (such as some arch commands and reading a file that doesn't exist on macOS), regardless those were tiny bugs, and the real fixer would be the packages from brew. I'll see if I can get homebrew working.
