### ISSUE TITLE
replace rustc-serialize with serde

### ISSUE THREAD

**Issue by dtolnay** [conradkdotcom/rooster#17]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by conradkleinespel** [comment]
@dtolnay Thanks for reporting that ! :+1: :heart:

Are you, by any chance, available to work on migrating Rooster to [Serde](https://crates.io/crates/serde)? If not, no worries, I know we all have plenty of things on our minds :wink:

**Comment by dtolnay** [comment]
No I'll leave it to you or one of the other contributors. It is not urgent of course.

**Comment by conradkleinespel** [comment]
@dtolnay Good to know ! Thanks again for reporting :smiley:

**Comment by conradkdotcom** [comment]
Quick recap of the work that needs to be done here.

Tasks:
- [ ] replace `rustc-serialize` with [`serde`](https://crates.io/crates/serde) and [`serde_json`](https://crates.io/crates/serde_json)
- [ ] bump the Rooster version to `2.5.1` in `Cargo.toml` so I can publish the new version to crates.io
- [ ] add yourself to the contributors' list in `README.md` in alphabetical order

If you have any questions, just let us know and we'll jump in to help.
