### ISSUE TITLE
seccomp

### ISSUE THREAD

**Issue by conradkdotcom** [conradkdotcom/rooster#28]
I'd like to introduce measures to protect us from a 3rd party library going rogue and sending data to the internet at some point. Imagine the maintainer for a library has his crates.io account hacked and for some reason we don't realise that an updated crate was hacked, that could mean disaster.

Would you know of any way we could prevent that from happening?

I was thinking of calling `seccomp` early in Rooster to prevent most syscalls, but a rogue library could hook into Rooster early on and defeat the `seccomp` rules. Another possibility I see is providing a shell wrapper around Rooster that would call `unshare` (or similar things on bsd/osx) to remove network access (and other dangerous things).

**Comment by yamnikov-oleg** [comment]
Concerns about third-party library from third-party sources make sense. To patch this vulnerabity, we could vendor all the third-party libraries right into the project's repository. That way no unwanted updates would come without audit.

**Comment by conradkdotcom** [comment]
Oh, yes, we would get diffs in Git of dependencies, wouldn't we? That could be cool indeed for auditing!

**Comment by conradkdotcom** [comment]
@yamnikov-oleg Oh, yes, we would get diffs in Git of dependencies, wouldn't we? That could be cool indeed for auditing!

**Comment by conradkdotcom** [comment]
Vendoring sounds good. Will make a new issue regarding that. Thanks @yamnikov-oleg  !
