### ISSUE TITLE
Add a way to store and retrieve files with Rooster

### ISSUE THREAD

**Issue by yamnikov-oleg** [conradkdotcom/rooster#35]
There is a possible use case for Rooster to store private keys, such as SSH or GPG keys, cryptocurrency account keys. But there is currently no convenient UI to do so. One can copy-paste file contents into `rooster add` input, but that wouldn't work with multiple lines.

I propose adding a way for users to `add` passwords from a file path and to `get` passwords into a file path. This change wouldn't require to create any new entities in the interface or invent new commands. There are at least two ways to do so:

1. Add an optional command-line flag `-p <path>` or `-f <file>` which can be used by different commands as a signal, that they have to interact with a specified file, rather than with stdin or clipboard. 
  Suggested usage: 
    * `rooster add prod-ssh master -f ./id_rsa`
    * `rooster get prod-ssh -f ./id_rsa`.

   This method has a flaw: `-f` flag is used sometimes as an input, sometimes as an output, therefore it might not always be clear what is does (as in `rooster change someapp -f ./pwd` for example).

2. Add an optional positional argument `[path]` to the commands that accept it.
  Suggested usage:
    * `rooster add prod-ssh master ./id_rsa`
    * `rooster get prod-ssh ./id_rsa`.

   Every command will have to have an explanation of this argument's function in the help text.

Same flag or argument could be added to `change`, `generate` and `regenerate` commands as well to ensure that commands act similarly.

**Comment by conradkdotcom** [comment]
@yamnikov-oleg Sorry for taking so long to reply, I have been busy with other stuff lately (mostly starting a new job, yay!). I think that having a way to store private keys would be super awesome ! And so I like your suggestions a lot !

I have a few questions about your suggestion:

- what do you think would be a good way to implement these commands without confusing the user as you showed in `1)` ?
- how does this integrate with `ssh` ? `ssh -i $(rooster get private-key)` ?
- what does `rooster get prod-ssh -f ./id_rsa` do ?

I am not against adding a new argument to the commands, as long as stuff works and is not surprising 😃

**Comment by yamnikov-oleg** [comment]
> what do you think would be a good way to implement these commands without confusing the user as you showed in 1) ?

After thinking a bit, I suppose it would be better to implement "key file" as a new entity in the Rooster ecosystem beside "password". It would require storage format upgrade, but that way there will be no confusion in the ways how different commands effect passwords and files (like `rooster generate prod-ssh` does not what would be expected), since the commands will be different.

Therefore, there could exist `add-file` and `get-file` commands:

```
rooster add-file prod-ssh ./id_rsa
rooster get-file prod-ssh ./id_rsa
or
rooster get-file prod-ssh > ./id_rsa
```

> how does this integrate with ssh ? ssh -i $(rooster get private-key) ?

`get-file` command could output file contents into the standard output if no path is provided, so this use case might be possible. 

> what does rooster get prod-ssh -f ./id_rsa do ?

It was supposed to save contents of `prod-ssh` key into ./id_rsa :smile:

I understand that the proposal is rather radical, so I suppose it might be delayed for some time to collect additional feedback and ideas.

**Comment by conradkdotcom** [comment]
Thanks for your answers! I definitely would like to have Rooster handle key encryption for me.

Just out of curiosity though, what workflow needs you to save the contents of something from Rooster into a file? The whole point of Rooster is that nothing is ever put in unencrypted files, no?

**Comment by yamnikov-oleg** [comment]
Actually, I thought of the feature as of single storage for all my passwords and private keys. I keep my rooster file in git repo and sync it with remote server to ensure its safety in case something happens to my PC.

I didn't take in account that most private keys would be encrypted by themselves.

**Comment by conradkdotcom** [comment]
@yamnikov-oleg Alright!

If you'd like to save a private key in Rooster, we could simply allow this:

```bash
rooster add MyPrivateKey NotApplicable -f id_rsa
```

...where you basically pass the password (well, in this case, the private key) via a file. And then to retrieve it, you could just call `rooster get MyPrivateKey > id_rsa`.

**Would that work for you?**

If so, feel free to submit a PR that reads the password from the `-f`/`--file` option instead of `STDIN` for the `change` and `add` commands. I'll be happy to merge!

**Comment by yamnikov-oleg** [comment]
I think I'll find a workaround for my purposes :)

**Comment by conradkdotcom** [comment]
@yamnikov-oleg Alright ! I'll go ahead and close this issue then ! Please let me know what you workaround is: I'm curious 😃
