### ISSUE TITLE
Rooster library aka. librooster

### ISSUE THREAD

**Issue by conradkdotcom** [conradkdotcom/rooster#39]
Rooster is going to get a companion library called `librooster`. This library will make Rooster's functionnality accessible without having to use Rooster itself. The end goal is to allow you to build custom software on top of Rooster's functionnality.

For instance, let's say you want to have custom password strength checks on your Rooster file. Well, with `librooster`, you can create a new Rust project, add just your custom check code and be done. No need to fiddle with Rooster's binary file format.

Or you want to build a web interface for Rooster. With `librooster` and [web development crates](http://arewewebyet.org/), you can get started quickly.

This issue will help track progress on the `librooster` project.

Feel free to comment below for any suggestions, questions or specific needs you might have! 👍

**Comment by yamnikov-oleg** [comment]
Basicly you mean to extract the `password` module and polish the API, right?

**Comment by conradkdotcom** [comment]
@yamnikov-oleg Exactly ! And other stuff too: `src/generate.rs`, `src/aes.rs`, `src/safe_string.rs`, src/safe_vec.rs` and some of `src/main.rs` (`get_password_file` and `get_password_store`, which will need a refactor to be reusable).

**Comment by conradkdotcom** [comment]
Just pushed a new command `rooster init` (which makes it easier to get started with Rooster when you first install it) and in the process made some progress towards `librooster` by cleaning up some old code.

**Comment by conradkdotcom** [comment]
Haven't had any time recently for this. If anyone is interested in working on this, feel free to say so and I'll reopen this issue. But for now, I have no time to work on this so I'll go ahead and close this.
