### ISSUE TITLE
Multiple users for same application

### ISSUE THREAD

**Issue by iia** [conradkdotcom/rooster#40]
If I understand correct, currently there can be only one user:password pair for an application.

Wouldn't it be nice to allow multiple user:password pairs for the same application? For example, for people who have two accounts for some service with different privileges? This could be a potential feature upgrade.

**Comment by conradkdotcom** [comment]
Hello @iia! Yes, you are right, currently there is only one password for each application name. So you can't have multiple passwords for one app named "Github", for instance.

The way I handle that is by having multiple entries in Rooster. For example:

```bash
rooster generate GoogleWork work@email.com # work account
rooster generate Google my@email.com       # personal account

rooster get ggl
```

When you do `rooster get ggl`, Rooster will understand that you meant either `GoogleWork` or `GooglePersonal` and ask you which password you want.

Does that meet your needs? If not, please explain in more detail what your use case is so we can try and find a way for Rooster to work for you.

**Comment by iia** [comment]
Hi,

Yah that works too.

I had a different mental model of the system previously. As in, when creating a new user:password pair the pair must belong to one application and the users of an application must be unique.

**Comment by conradkdotcom** [comment]
Great to hear that works for you 😃 

FYI the only thing unique in Rooster is the app name. Usernames and passwords can be duplicated.

If you have any other questions, feel free to open a new issue or get back via email.

Cheers !
